services:
    mysql:
        image: mysql:9.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: document_manager
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - '0.0.0.0:3306:3306'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10

    api:
        build: .
        container_name: api
        ports:
            - '0.0.0.0:3000:3000'
            - '0.0.0.0:8080:8080'
        environment:
            DATABASE_URL: 'mysql://root:@mysql:3306/document_manager'
            PORT: 3000
        depends_on:
            mysql:
                condition: service_healthy
